name:                gtk-sni-tray
version:             0.1.0.0
github:              "IvanMalison/gtk-sni-tray"
license:             BSD3
author:              "Ivan Malison"
maintainer:          "IvanMalison@gmail.com"
copyright:           "2018 Ivan Malison"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A standalone StatusNotifierItem/AppIndicator tray
category:            System

description:         Please see the README on Github at <https://github.com/IvanMalison/gtk-sni-tray#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - dbus
  - gi-dbusmenugtk3
  - gi-gdk
  - gi-gdkpixbuf >= 2.0.15
  - gi-glib
  - gi-gtk >= 3.0.21
  - hslogger
  - mtl
  - status-notifier-item
  - directory
  - text
  - transformers
  - unix

library:
  source-dirs: src
  pkg-config-dependencies:
    - gtk+-3.0

executables:
  gtk-sni-tray-standalone:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtk-sni-tray
