resolver: lts-11.7
packages:
- .
extra-deps:
- dbus-1.0.1
- dbus-hslogger-0.1.0.1
- gi-dbusmenu-0.4.1
- gi-dbusmenugtk3-0.4.1
- gi-gdk-3.0.15
- gi-gdkpixbuf-2.0.16
- gi-gio-2.0.16
- gi-gtk-3.0.21
- gi-pango-1.0.16
- gio-0.13.4.1
- gtk-strut-0.1.2.1
- gtk3-0.14.9
- haskell-gi-0.21.2
- haskell-gi-base-0.21.1
- spool-0.1
- status-notifier-item-0.3.0.0
nix:
  packages:
    - gcc
    - gobjectIntrospection
    - gtk3
    - libdbusmenu-glib
    - libdbusmenu-gtk3
    - libxml2
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
