resolver: lts-11.0
packages:
- .
- location:
    git: https://github.com/IvanMalison/haskell-dbus
    commit: b2f463be3d702e721f1fef41a5e07b45e60ec737
  extra-dep: true
- location:
    git: https://github.com/IvanMalison/status-notifier-item
    commit: 211f4759e08d27b2bacf1061cf03d4dc573d0f39
  extra-dep: true
# - location: ../haskell-dbus
#   extra-dep: true
# - location: ../status-notifier-item
#   extra-dep: true
extra-deps:
  - spool-0.1
  - gio-0.13.4.1
  - gi-dbusmenugtk3-0.4.1
  - gi-dbusmenu-0.4.1
  - gi-gdk-3.0.15
  - gi-gdkpixbuf-2.0.15
  - gi-gtk-3.0.21
  - gi-gio-2.0.16
  - gi-pango-1.0.16
